FROM ubuntu:24.04

RUN apt-get update
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN apt-get -qq -y install curl wget unzip zip

RUN curl -s "https://get.sdkman.io" | bash
RUN chmod a+x "$HOME/.sdkman/bin/sdkman-init.sh"
RUN source "$HOME/.sdkman/bin/sdkman-init.sh"

ADD install-java.sh /home/ubuntu/install-java.sh
RUN chmod +x /home/ubuntu/install-java.sh
WORKDIR /home/ubuntu

CMD ["/bin/bash"]

